services:
  - type: web
    name: blackticket-backend
    runtime: node
    region: oregon
    plan: free
    buildCommand: npm ci && npx prisma generate && npm run build
    startCommand: node dist/src/main.js
    healthCheckPath: /
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
